### ISSUE TITLE
Do not print usage when I already have template

### ISSUE THREAD

**Issue by pgrange** [n0vember/nocloud#10]
When I try to download a template I already have, nocloud displays its usage:
```
 vmtemplate -d debian8
you already have a template called debian8
usage : vmtemplate -d TEMPLATE_NAME
   or : vmtemplate -c TEMPLATE_NAME -i ISO_NAME
  -d : download a template. TEMPLATE_NAME is one of archlinux debian8 centos7
  -c : create a template ou t of iso
  -i : specify isoName
  -h : display this help
```

I think it would be nicer to just display the message:
```
you already have a template called debian8
```

Note that status code is 0 so the command does not fail and this is OK.

**Comment by n0vember** [comment]
This was worse than that : template name verification was only made on template download, not on template creation. This is fixed in commit b3d7b00b9178fe8b58e01f9a2406e5299c28c1b4.

Also integrated your remark on not using usage function. I tend to do this on any exit, but it's not always necessary.
